package persistence

// HTML template for the report
const HTMLTemplate = `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Website Health Check Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
            background-color: #f5f5f5;
        }
        .container {
            max-width: 800px;
            margin: 0 auto;
            background-color: white;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }
        h1 {
            color: #333;
            text-align: center;
            border-bottom: 2px solid #4CAF50;
            padding-bottom: 10px;
        }
        .timestamp {
            text-align: center;
            color: #666;
            margin-bottom: 30px;
        }
        .summary {
            display: flex;
            justify-content: space-around;
            margin-bottom: 30px;
        }
        .stat-box {
            text-align: center;
            padding: 15px;
            border-radius: 5px;
            flex: 1;
            margin: 0 10px;
        }
        .success-box {
            background-color: #d4edda;
            border: 1px solid #c3e6cb;
            color: #155724;
        }
        .fail-box {
            background-color: #f8d7da;
            border: 1px solid #f5c6cb;
            color: #721c24;
        }
        .total-box {
            background-color: #d1ecf1;
            border: 1px solid #bee5eb;
            color: #0c5460;
        }
        .section {
            margin-bottom: 30px;
        }
        .section h2 {
            color: #333;
            border-left: 4px solid #4CAF50;
            padding-left: 10px;
        }
        .fail-section h2 {
            border-left-color: #f44336;
        }
        .site-item {
            padding: 10px;
            margin: 5px 0;
            border-radius: 4px;
            display: flex;
            justify-content: space-between;
            align-items: center;
        }
        .success-item {
            background-color: #d4edda;
            border-left: 4px solid #28a745;
        }
        .fail-item {
            background-color: #f8d7da;
            border-left: 4px solid #dc3545;
        }
        .site-name {
            font-weight: bold;
        }
        .site-status {
            font-size: 0.9em;
        }
        .error-code {
            color: #dc3545;
            font-weight: bold;
        }
        .site-link {
            color: #007bff;
            text-decoration: none;
            font-size: 0.8em;
        }
        .site-link:hover {
            text-decoration: underline;
        }
        .footer {
            text-align: center;
            margin-top: 30px;
            padding-top: 20px;
            border-top: 1px solid #ddd;
            color: #666;
            font-size: 0.9em;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Website Health Check Report</h1>
        <div class="timestamp">Generated on: {{.Timestamp}}</div>
        
        <div class="summary">
            <div class="stat-box success-box">
                <h3>{{.HealthyCount}}</h3>
                <p>Healthy Sites</p>
            </div>
            <div class="stat-box fail-box">
                <h3>{{.FailedCount}}</h3>
                <p>Failed Sites</p>
            </div>
            <div class="stat-box total-box">
                <h3>{{.TotalCount}}</h3>
                <p>Total Sites</p>
            </div>
        </div>

        {{if .HealthySites}}
        <div class="section">
            <h2>Healthy Sites</h2>
            {{range .HealthySites}}
            <div class="site-item success-item">
                <span class="site-name">{{.Name}}</span>
                <span class="site-status">OK</span>
            </div>
            {{end}}
        </div>
        {{end}}

        {{if .FailedSites}}
        <div class="section fail-section">
            <h2>Failed Sites</h2>
            {{range .FailedSites}}
            <div class="site-item fail-item">
                <div>
                    <div class="site-name">{{.Name}}</div>
                    <a href="{{.Link}}" class="site-link" target="_blank">{{.Link}}</a>
                </div>
                <div>
                    <span class="error-code">Error: {{.Code}}</span>
                </div>
            </div>
            {{end}}
        </div>
        {{end}}

        <div class="footer">
            Report generated by Go-Gin-Gee Health Checker
        </div>
    </div>
</body>
</html>
`
