basePath: /api
info:
  contact:
    email: mazeyqian@gmail.com
    name: Cheng
    url: https://github.com/mazeyqian
  description: API in Golang with Gin Framework
  license:
    name: MIT
    url: https://github.com/chengchuu/go-gin-gee/blob/main/LICENSE
  version: "1.0"
paths: {}
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
